Fix: Handle non-rewindable body streams in Rack::Proxy
Rackup::Handler::WEBrick::Input does not implement rewind under Pact 2 / Rack 3 / Rails 8

The `rewind` method is called on the `body_stream` of the `target_request`. However, in
some cases, such as when using `Rackup::Handler::WEBrick::Input`, the `body_stream`
may not implement the `rewind` method.

This can lead to errors when trying to rewind a non-rewindable body stream.

```
NoMethodError: undefined method 'rewind' for an instance of Rackup::Handler::WEBrick::Input
```

This error then, confusingly, manifests as a 500 Internal Server Error from Pact.

```
ERROR ThreadId(11) pact_verifier: No pacts found for provider 'blah' matching the given consumer version selectors in pact broker 'http://127.0.0.1:9002': IO Error - Request to pact broker path 'blah' failed: 500 Internal Server Error. URL: 'http://127.0.0.1:9002'
```
nb: the `http://127.0.0.1:9002` is the default proxy server from pact, spun up by rack-proxy.